---
deployment:
  tasks:
    - export DEPLOYPATH=/home11/bakisgr/public_html/react-test/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/which node > $DEPLOYPATH/node-check.txt 2>&1 || true
    - /usr/bin/which npm >> $DEPLOYPATH/node-check.txt 2>&1 || true
    - /usr/bin/which php >> $DEPLOYPATH/node-check.txt 2>&1 || true